server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_hotel
    username: root
    password: neel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#spring.security.user.name=neel
#spring.security.user.password=neel
#spring.security.user.roles=Admin