server:
  port: 8085


spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/neel0086/microservices-config
          clone-on-start: true

#spring.security.user.name=neel
#spring.security.user.password=neel
#spring.security.user.roles=Admin