server:
  port: 8083


spring:
  data:
    mongodb:
      uri: mongodb+srv://neel:neel@ratings.l9tewsm.mongodb.net/?retryWrites=true&w=majority
      database: microservices
#spring.security.user.name=neel
#spring.security.user.password=neel
#spring.security.user.roles=Admin